import type { Metadata } from "next";
import "@/styles/globals.scss";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://checkout.razorpay.com/v1/checkout.js"
        ></script>
        <link rel="icon" href="/favicon.svg" />
        <script
          src="https://widgets.in.webengage.com/js/service-worker.js"
        ></script>
        <script
          type="text/javascript"
          id="_webengage_script_tag"
          dangerouslySetInnerHTML={{
            __html: `var webengage;!function(e,t,n,i,o){function s(e,t){e[t[t.length-1]]=function(){a.__queue.push([t.join("."),arguments])}}var r,g,a=e[n],c="init options track screen onReady".split(" "),l="feedback survey notification".split(" "),p="options render clear abort".split(" "),u="Open Close Submit Complete View Click".split(" "),f="identify login logout setAttribute".split(" ");if(!a||!a.__v){for(e[n]=a={__queue:[],is_spa:1,__v:"6.0",user:{}},r=0;r<c.length;r++)s(a,[c[r]]);for(r=0;r<l.length;r++){for(a[l[r]]={},g=0;g<p.length;g++)s(a[l[r]],[l[r],p[g]]);for(g=0;g<u.length;g++)s(a[l[r]],[l[r],"on"+u[g]])}for(r=0;r<f.length;r++)s(a.user,["user",f[r]]);setTimeout(function(){var e=t.createElement("script"),n=t.getElementById("_webengage_script_tag");e.type="text/javascript",e.async=!0,e.src=("https:"==t.location.protocol?"https://widgets.in.webengage.com":"http://widgets.in.webengage.com")+"/js/webengage-min-v-6.0.js",n.parentNode.insertBefore(e,n)})}}(window,document,"webengage"),webengage.init('in~82617217');`,
          }}
        ></script>
         
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-R0QPWVG6LX"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-R0QPWVG6LX');
          `,
          }}
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
          (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "lty1y3p17h");`,
          }}
        ></script>
      </head>
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
